/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fibers_FibersJavaAPI */

#ifndef _Included_Fibers_FibersJavaAPI
#define _Included_Fibers_FibersJavaAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fibers_FibersJavaAPI
 * Method:    convertThreadToFiber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Fibers_FibersJavaAPI_convertThreadToFiber
  (JNIEnv *, jclass, jint);

/*
 * Class:     Fibers_FibersJavaAPI
 * Method:    switchToFiber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Fibers_FibersJavaAPI_switchToFiber
  (JNIEnv *, jclass, jint);

/*
 * Class:     Fibers_FibersJavaAPI
 * Method:    deleteFiber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Fibers_FibersJavaAPI_deleteFiber
  (JNIEnv *, jclass, jint);

/*
 * Class:     Fibers_FibersJavaAPI
 * Method:    createFiber
 * Signature: (ILFibers/FiberStartRoutine;I)I
 */
JNIEXPORT jint JNICALL Java_Fibers_FibersJavaAPI_createFiber
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
